src/business/rulesbeans/FinalOrderBean.java
package business.rulesbeans;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

import business.exceptions.BackendException;
import business.externalinterfaces.Address;
import business.externalinterfaces.CartItem;
import business.externalinterfaces.CreditCard;
import business.externalinterfaces.DynamicBean;
import business.externalinterfaces.ShoppingCart;
import business.util.Pair;



public class FinalOrderBean implements DynamicBean {
	private static final Logger LOG = Logger.getLogger(FinalOrderBean.class
			.getPackage().getName());
    
	private ShoppingCart shopCart;
	public FinalOrderBean(ShoppingCart sc){		
		shopCart = sc;
	}
	
	
	///////bean interface for shopping cart
	
	public Address getShippingAddress() {
		return shopCart.getShippingAddress();
	}
    public Address getBillingAddress(){
		return shopCart.getBillingAddress();
	}
    public CreditCard getPaymentInfo(){
		return shopCart.getPaymentInfo();
	}
    public List<CartItem> getCartItems(){
		return shopCart.getCartItems();
	}
    /** 
     * This is a collection of pairs indicating
     * the quantity requested vs quantity avail
     * for each line item in the shopping cart
     * 
     * If return value is empty, this indicates an error condition
     * @return
     */
    
    public List<Pair> getRequestedAvailableList() throws BackendException { 	
    	List<Pair> retVal = computeRequestedAvailableList(shopCart);
    	if(!shopCart.isEmpty() && retVal.isEmpty()) {
    		LOG.severe("FinalOrderBean.getRequestedAvailableList() returned an empty list");
    		throw new BackendException("Quantity pairs not found");
    		
    	}
    	return retVal;
    }
    
    /** Find a way to implement this -- either implement getProductTable or do a different way */
    public static List<Pair> computeRequestedAvailableList(ShoppingCart shoppingCart) throws BackendException {
    	//stub
    	Pair p1 = new Pair(1,1);
    	Pair p2 = new Pair(2,2);
    	List<Pair> list = Arrays.asList(p1,p2);
    	return list;
    	
//    	
//    	if(shoppingCart == null) return null;
//    	List<CartItem> cartItems = shoppingCart.getCartItems();
//    	//HashMap<Integer,Integer> reqAvailMap = new HashMap<Integer,Integer>();
//    	List<Pair> reqAvailList = new ArrayList<Pair>();
//    	TwoKeyHashMap<Integer,String,Product> prodTable = (new ProductSubsystemFacade()).getProductTable();
//    	CartItem nextItem = null;
//    	String nextName = null;
//    	String nextQuantRequested = null;
//    	Integer nextQuantAvail = null;
//    	Product nextProduct = null;
//    	Iterator<CartItem> it = cartItems.iterator();
//    	while(it.hasNext()){
//    		nextItem = (CartItem)it.next();
//    		nextQuantRequested = nextItem.getQuantity();
//    		nextName = nextItem.getProductName();
//    		nextProduct = (Product)prodTable.getValWithSecondKey(nextName);
//    		nextQuantAvail = nextProduct.getQuantityAvail();
//    		reqAvailList.add(new Pair(Integer.parseInt(nextQuantRequested), 
//    					   nextQuantAvail));
//    		
//    	}
//    	System.out.println(reqAvailList);
//    	return reqAvailList;
    }
    
	///////////property change listener code
    private PropertyChangeSupport pcs = 
    	new PropertyChangeSupport(this);
    public void addPropertyChangeListener(PropertyChangeListener pcl){
	 	pcs.addPropertyChangeListener(pcl);
	}
	public void removePropertyChangeListener(PropertyChangeListener pcl){	
    	pcs.removePropertyChangeListener(pcl);
    }
}

src/business/rulesbeans/PaymentBean.java
package business.rulesbeans;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

import business.externalinterfaces.*;

public class PaymentBean implements DynamicBean {
	private CreditCard cc;
	private Address addr;
	public PaymentBean(Address addr, CreditCard cc) {
		this.addr = addr;
		this.cc = cc;
	}
	//////////// bean interface for address and credit card
	public String getCity() {
        return addr.getCity();
    }
 
    public String getState() {
        return addr.getState();
    }
 
     public String getStreet() {
        return addr.getStreet();
    }
 
    public String getZip() {
        return addr.getZip();
    }
    public String getCardNum(){
    	
    	return cc.getCardNum();
    }
    public String getExpirationDate(){
    	return cc.getExpirationDate();
    }
    public String getNameOnCard() {
    	return cc.getNameOnCard();
    }
    
    public String getCardType() {
    	return cc.getCardType();
    }
	
	///////////property change listener code
    private PropertyChangeSupport pcs = 
    	new PropertyChangeSupport(this);
    public void addPropertyChangeListener(PropertyChangeListener pcl){
	 	pcs.addPropertyChangeListener(pcl);
	}
	public void removePropertyChangeListener(PropertyChangeListener pcl){	
    	pcs.removePropertyChangeListener(pcl);
    }

}

WebContent/WEB-INF/bodyfragments/_admin_catalog.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
 

<script>
	function checkCatalogName(){
		if($("#catalogName").val() == ""){
			$("#catalogNameError").show();
			return false;
		}
		else{
			$("#catalogNameError").hide();
			return true;
		}
	}
	
</script> 
<br>
<h3>Catalogs List</h3>
<hr>
	<form action="admin/catalog" method="post">        
        <div class="row">
		  <div class="col-lg-6"> 
		  	<div class="clo-lg-1">
		    	<span style="color:red; display:none; padding-left:10px;" id="catalogNameError">You must input catalog name</span>
		    </div>
		    <div class="input-group clo-lg-5">
		      <input type="text" id="catalogName" name="name" style="width:100%" class="form-control" placeholder="Catalog name here...">
		      <span class="input-group-btn">
		        <input class="btn btn-secondary" type="submit" onclick="return checkCatalogName();" value="Add">
		      </span>		    
		    </div>		   
		  </div>
		</div>
	</form> 
    <table id="table" class="table">
    	<thead><td>Id</td><td>Name</td><td></td></thead>
    	<tbody>
    		<c:forEach items = "${catalogs}" var="catalog">
    		<tr>
    			<td>${catalog.id}</td>
    			<td>${catalog.name}</td>
    			<td><a href="admin/catalog/${catalog.id}" class="action" >Delete</a></td>
    		</tr>
    		</c:forEach>       	
    	</tbody>
    </table> 
 

WebContent/WEB-INF/bodyfragments/_admin_home.jsp
<br>

Select maintain task from left side...

WebContent/WEB-INF/bodyfragments/_admin_product_add.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"  %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>

 <script type="text/javascript">
     $(function () {
         $('#mfg').datepicker();
     });
 </script>
<br>
<c:choose>
	<c:when test="${empty isEdit}">
		<h3>Add new product</h3>
	</c:when>
	<c:otherwise>
		<h3>Edit product</h3>
	</c:otherwise>
</c:choose>
<hr>
<form:form action="admin/product"  modelAttribute="newProduct" class="form-horizontal" enctype="multipart/form-data">
		<fieldset>		

			<form:errors path="*" cssClass="alert alert-danger" element="div"/>
			 
			<form:input id="productId" path="productId" type="hidden"  />
			 
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon1">Name</span>
			  <form:input id="name" path="name" type="text"  placeholder="Product name" class="form-control" aria-describedby="basic-addon1"/>			  
			</div><form:errors path="name" cssClass="text-danger"/>
			<br>			 
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon7">Category</span>
			  <form:select path="category" class="form-control" aria-describedby="basic-addon7">
			  		<form:options items="${catalogs}" itemLabel="name" itemValue="id" />
			  </form:select>
			</div>
			<br>
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon2">UnitPrice</span>
			  <form:input id="unitPrice" path="unitPrice" type="text"  placeholder="0.0" class="form-control" aria-describedby="basic-addon2"/>
			  <form:errors path="unitPrice" cssClass="text-danger"/>
			</div>
			<br>
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon7">Mfg Date</span>
			  <form:input id="mfg" path="mfg" type="text"  placeholder="MM/DD/YYYY" class="form-control" aria-describedby="basic-addon7"/>			  			 
			  <form:errors path="mfg" cssClass="text-danger"/>
			</div>
			<br>
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon4">UnitsInStock</span>
			  <form:input id="unitsInStock" path="unitsInStock" type="text"  placeholder="0" class="form-control" aria-describedby="basic-addon4"/>
			  <form:errors path="unitsInStock" cssClass="text-danger"/>
			</div>
			<br> 
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon5">Product Image</span>
			  <form:input id="productImage" path="productImage" type="file"	class="form-control" aria-describedby="basic-addon5"/>
			  <form:errors path="productImage" cssClass="text-danger"/>
			</div>
			<br> 
			<div class="input-group">
			  <span class="input-group-addon" id="basic-addon6">Description</span>			  
			  <form:textarea id="description" path="description" rows = "2"  class="form-control" aria-describedby="basic-addon6"/>
			</div>	


			<br>
			<div class="form-group">
				<div class="col-lg-offset-2 col-lg-10">
					<input type="submit" id="btnAdd" class="btn btn-secondary" value ="Add"/>
				</div>
			</div>
			
		</fieldset>
	</form:form>



WebContent/WEB-INF/bodyfragments/_admin_product_list.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<br>

<h3>Products List</h3>
<hr>
<table id="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Catalog</th>
			<th>Name</th>
			<th>Quantity</th>
			<th>Price</th>
			<th>MFG Date</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<c:forEach items="${products}" var="product">
			<tr>
				<td>${product.id}</td>
				<td>${product.catalog.name}</td>
				<td>${product.name}</td>
				<td>${product.quantityAvail}</td>
				<td>${product.unitPrice}</td>
				<td>${product.mfg}</td>
				<td><a href="product/${product.id}" class="action">View</a>
				<a href="admin/products/edit/${product.id}"class="action">Edit</a>
				<a href="admin/products/delete/${product.id}" class="action">Delete</a></td>
			</tr>
		</c:forEach>
	</tbody>
</table>

WebContent/WEB-INF/bodyfragments/_agreement_form.jsp

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<br>
<br>
<div class="row">
<div class="col-md-offset-1 ">  
	<h3>Terms and Conditions</h3>
	Any Items purchased from this site adhere to the terms and conditions
	depicted in this document. You will need to accept the Terms and
	Conditions depicted here in order to purchase anything from this site.
</div>
</div>

<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-2">		
		<a class="btn btn-primary" href="myordersummary">Accept and Process</a>
	</div>
	<div class="col-md-2">
		<a class="btn btn-primary" href="shoppingcart">Back to Shopping	Cart </a>
	</div>
</div>

WebContent/WEB-INF/bodyfragments/_checkout_address.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"  %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<script type="text/javaScript">

$(document).ready(function(){
	$("#addressSelection").hide();
	$("#selectShipAddress").click(function(){ 
		$("#shippingaddress-dialog" ).dialog({
		      resizable: false,
		      maxHeight:400,
		      width:600,
		      modal: true,
		      buttons: {
		        Cancel: function() {
		          $(this).dialog("close");
		        }
		      }
		    });
		return false;
	});
	
	$("#selectBillAddress").click(function(){
		$("#billingaddress-dialog" ).dialog({
		      resizable: false,
		      maxHeight:400,
		      width:600,
		      modal: true,
		      buttons: {
		        Cancel: function() {
		          $(this).dialog("close");
		        }
		      }
		    });
		return false;
	});
	
	
	$("#shippingaddress-dialog .address-selected").click(function(){
		$("#shippingaddress-dialog" ).dialog("close");
		var td = $(this).parent().parent().children();
		$("#streetShipping").val($(td[0]).text());
		$("#cityShipping").val($(td[1]).text());
		$("#stateShipping").val($(td[2]).text());
		$("#zipShipping").val($(td[3]).text());
	})
	
	$("#billingaddress-dialog .address-selected").click(function(){
		$("#billingaddress-dialog" ).dialog("close");
		var td = $(this).parent().parent().children();
		$("#streetBilling").val($(td[0]).text());
		$("#cityBilling").val($(td[1]).text());
		$("#stateBilling").val($(td[2]).text());
		$("#zipBilling").val($(td[3]).text());
	})
	
});


function onBillingSameAsShipping(){
	document.getElementById("stateBilling").value = document.getElementById("stateShipping").value;
	document.getElementById("cityBilling").value = document.getElementById("cityShipping").value;
	document.getElementById("zipBilling").value = document.getElementById("zipShipping").value;
	document.getElementById("streetBilling").value = document.getElementById("streetShipping").value;
}
</script>

<style>
div.hidden {
    display: none;
}

div.shown {
    display: none;
}

.table{
	width:100%;
	font-size:smaller;
}
</style>

<br>
<h3>Shipping Information</h3>
<hr/>

<c:if test="${fn:length(exception) gt 0}">
 	<div class="alert alert-danger">${exception}</div>
</c:if>
<form:form action="mypaymentinfo" modelAttribute="checkoutmodel" method="POST">
		<div class="row">
			<div class="col-md-4">
				<div class="row">				
					<h4>Shipping Address</h4>
				</div>				 
				<div class="input-group">
				  <span class="input-group-addon">Street</span>
				  <form:input id="streetShipping" path="shippingAddress.street" type="text"  placeholder="101 N COURT" class="form-control"/>			  
				</div><form:errors path="shippingAddress.street" cssClass="text-danger"/>
				<div class="input-group">
				  <span class="input-group-addon">City</span>
				  <form:input id="cityShipping" path="shippingAddress.city" type="text"  placeholder="FAIRFIELD" class="form-control"/>			  
				</div><form:errors path="shippingAddress.city" cssClass="text-danger"/>				 
				<div class="input-group">
				  <span class="input-group-addon">State</span>
				  <form:input id="stateShipping" path="shippingAddress.state" type="text"  placeholder="IA" class="form-control"/>			  
				</div><form:errors path="shippingAddress.state" cssClass="text-danger"/>				 
				<div class="input-group">
				  <span class="input-group-addon">Zip</span>
				  <form:input id="zipShipping" path="shippingAddress.zip" type="text"  placeholder="52556" class="form-control"/>			  
				</div><form:errors path="shippingAddress.zip" cssClass="text-danger"/>				
			</div> 
			<div class="col-md-4">
				<div class="row">				
					<h4>Billing Address</h4>
				</div>
				<div class="input-group">
				  <span class="input-group-addon" id="basic-addon1">Street</span>
				  <form:input  id="streetBilling" path="billingAddress.street" type="text"  placeholder="101 N COURT" class="form-control"/>			  
				</div><form:errors path="billingAddress.street" cssClass="text-danger"/>
				<div class="input-group">
				  <span class="input-group-addon" id="basic-addon2">City</span>
				  <form:input id="cityBilling" path="billingAddress.city" type="text"  placeholder="FAIRFIELD" class="form-control"/>			  
				</div><form:errors path="billingAddress.city" cssClass="text-danger"/>				 
				<div class="input-group">
				  <span class="input-group-addon">State</span>
				  <form:input id="stateBilling" path="billingAddress.state" type="text"  placeholder="IA" class="form-control"/>			  
				</div><form:errors path="billingAddress.state" cssClass="text-danger"/>				 
				<div class="input-group">
				  <span class="input-group-addon">Zip</span>
				  <form:input id="zipBilling" path="billingAddress.zip" type="text"  placeholder="52556" class="form-control"/>			  
				</div><form:errors path="billingAddress.zip" cssClass="text-danger"/>				
			</div>
		</div>
		<div class="row">
		    	 <div class="checkbox">
		      		<label><input type="checkbox" value="" onclick="if(this.checked){onBillingSameAsShipping()}" />Billing Same as shipping</label>
		    	
		     		 <label><form:checkbox path="saveShippingAddress"  id="chkBoxSaveShipping" onClick="onSaveShipping()" />Save Shipping address</label>
		     		 <input type="hidden" id="saveShipping" value="${saveShipping }"></input>
		    	
		     		 <label><form:checkbox path="saveBillingAddress"  onClick="onSaveBilling()" />Save Billing Address</label>
		     		 <input type="hidden" id="saveBilling" value="${saveBilling }"></input>
		    	</div>
		</div>
		<div class="row">
		<div class="col-md-2 text-center">
			<button  class="btn btn-primary" role="button" id = "selectShipAddress">Select Ship Address</button>		
		</div>
		<div class="col-md-2 text-center">
			<button  class="btn btn-primary" role="button" id = "selectBillAddress">Select Bill Address</button>
		</div>
		<div class="col-md-2 text-center">		
			<input  class="btn btn-primary" role="button" id = "checkoutBtn" type="submit" value="Checkout" />		
		</div>
		<div class="col-md-2 text-center">
			<a  class="btn btn-primary" role="button"  href="shoppingcart" id = "checkoutBtn">Back to Cart</a>		
		</div>
	</div>
	</form:form>
	
<div id="billingaddress-dialog" title="Select billing address" style="display:none;">
	<table class="table">
		<c:forEach items="${allBillAddresses}" var="add" varStatus="vs">
 			<tr><td>${add.street}</td><td>${add.city}</td><td>${add.state}</td><td>${add.zip}</td><td><button type="button" class="btn btn-warning address-selected">Bill to this address</button></td></tr> 
		</c:forEach>
	</table>
</div>	
	
<div id="shippingaddress-dialog" title="Select shipping address" style="display:none;">
	<table class="table">
		<c:forEach items="${allShipAddresses}" var="add" varStatus="vs">
 			<tr><td>${add.street}</td><td>${add.city}</td><td>${add.state}</td><td>${add.zip}</td><td><button type="button" class="btn btn-warning address-selected">Ship to this address</button></td></tr>
		</c:forEach>
	</table>
</div>

WebContent/WEB-INF/bodyfragments/_final_order.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<br />
<h3>Order Summary</h3>
<hr>

<c:if test="${fn:length(exception) gt 0}">
 	<div class="alert alert-danger">${exception}</div>
</c:if>
<b>Order Item :</b>
<c:forEach var="cdi" items="${cartDataItems}" varStatus="rowCounter">
	<div class="row">
		<div class="col-md-4">
			<div style="float:left;">
				<p class="text-primary">
					<b>${cdi.itemName }</b> <input type="hidden" id="cdiId${rowCounter.index }" value="${cdi.price }"></input>
				</p>
				<p>Price: ${cdi.price }</p>
			</div>					
			<div class="small-thumbnail">
				<a href="product/${cdi.productId}"><img src="static/images/${cdi.productId}.png" /></a>
			</div>
		</div>				
		<div class="col-md-1">
			<p>
				<b>$${cdi.price }</b>
			</p>
			<p class="text-muted">Each</p>
		</div>
		<div class="col-md-2">
			<p><b>${cdi.quantity}</b><p>
			<p>Quantity</p>
		</div>

		<div class="col-md-2">
			<p>
				<label class="subTotal" id="subTotal${rowCounter.index}">
					<fmt:formatNumber value="${cdi.price*cdi.quantity}" maxFractionDigits="2" />
				</label>
			</p>
			<p class="text-muted">Total</p>
		</div>
	</div>
	<hr
		style="background: #454545; color: #ddd; clear: both; float: none; width: 100%; height: .1em; margin: 0 0 1.45em; border: none;" />
</c:forEach>
<div class="col-md-2">
		<p class="text-primary">
			Total: $ <label id="total">${total}</label>
		</p>
</div>
<br/>
<hr>
<div class="col-md-10">
	<b>Ship To:</b> ${checkoutmodel.shippingAddress.street} ${checkoutmodel.shippingAddress.city} ${checkoutmodel.shippingAddress.state}, ${checkoutmodel.shippingAddress.zip}
</div>
<br/>
<hr>
<div class="col-md-10">
	<b>Payment :</b> ${checkoutmodel.creditCard.cardType} - ${fn:substring(checkoutmodel.creditCard.cardNum, fn:length(checkoutmodel.creditCard.cardNum) - 4, fn:length(checkoutmodel.creditCard.cardNum))}
</div>  
<br/>
<hr>
<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-2  text-center">
		<form action="myplaceorder">
			<button class="btn btn-primary" type="submit" id="checkoutBtn">Submit Order</button>
		</form>
	</div>
	<div class="col-md-2  text-center">
		<form action="${pageContext.request.contextPath}/" method="GET">
			<button class="btn btn-primary" type="submit">Continue Shopping</button>
		</form>
	</div>	
</div> 

WebContent/WEB-INF/bodyfragments/_home.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
    <!-- Page Content -->
    <div class="container-fluid">

        <div class="row-fluid">
 

            <div class="col-md-12">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="static/images/h1.png" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="static/images/h4.png" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="static/images/h2.png" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="static/images/h3.png" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

				<p class="hot">Most popular of this week <img src="static/images/hot.gif" /></p>
                <div class="row">

                    <c:forEach items="${products}" var="product">
					    <div class="col-sm-2 col-lg-2 col-md-2">
	                        <div class="thumbnail">
	                            <a href="product/${product.id}"><img src="static/images/${product.id}.png" alt=""></a>
	                            <div class="caption">
	                                <h4 class="pull-right">$${product.unitPrice}</h4>
	                                <h5><a href="product/${product.id}">${product.name}</a>
	                                </h5>
	                              <%--   <p>${product.description}</p> --%>
	                            </div>
	                            <div class="ratings">
	                                <p class="pull-right">
	                                	<span class="glyphicon glyphicon-hand-right"></span>
	                                	<span>${product.review}</span>
	                                </p>
	                                <p>
	                                	<c:set var = "rating" value="${product.rating}" />
	                                	<c:if test="${rating eq 0}">
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                	</c:if>
	                                	<c:if test="${rating eq 1}">
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                	</c:if>
	                                	<c:if test="${rating eq 2}">
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                	</c:if>
	                                	<c:if test="${rating eq 3}">
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                	</c:if>
	                                	<c:if test="${rating eq 4}">
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star-empty"></span>
	                                	</c:if>
	                                	<c:if test="${rating eq 5}">
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                		<span class="glyphicon glyphicon-star"></span>
	                                	</c:if>
	                                </p>
	                            </div>
	                        </div>
	                    </div>						
					</c:forEach>                
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->